// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAluOeFF-oeeYMf7qe3b2vQyMsO_0oetW8',
    appId: '1:44853351550:web:3b089746d5031ce82cf42f',
    messagingSenderId: '44853351550',
    projectId: 'izakaya-staff-app',
    authDomain: 'izakaya-staff-app.firebaseapp.com',
    storageBucket: 'izakaya-staff-app.firebasestorage.app',
    measurementId: 'G-9HX2780DVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfKL9XaRxU4twn02ivPi1fxc8tfvTskjE',
    appId: '1:44853351550:android:6ec78171349434292cf42f',
    messagingSenderId: '44853351550',
    projectId: 'izakaya-staff-app',
    storageBucket: 'izakaya-staff-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTxfFxaBpCPexSDbEaZacmneADtnHxKqI',
    appId: '1:44853351550:ios:562eecdf3961b3792cf42f',
    messagingSenderId: '44853351550',
    projectId: 'izakaya-staff-app',
    storageBucket: 'izakaya-staff-app.firebasestorage.app',
    iosBundleId: 'com.example.izakayaStaffApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTxfFxaBpCPexSDbEaZacmneADtnHxKqI',
    appId: '1:44853351550:ios:562eecdf3961b3792cf42f',
    messagingSenderId: '44853351550',
    projectId: 'izakaya-staff-app',
    storageBucket: 'izakaya-staff-app.firebasestorage.app',
    iosBundleId: 'com.example.izakayaStaffApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAluOeFF-oeeYMf7qe3b2vQyMsO_0oetW8',
    appId: '1:44853351550:web:a666c385766cf3612cf42f',
    messagingSenderId: '44853351550',
    projectId: 'izakaya-staff-app',
    authDomain: 'izakaya-staff-app.firebaseapp.com',
    storageBucket: 'izakaya-staff-app.firebasestorage.app',
    measurementId: 'G-EL1MXHKKTY',
  );
}
